workspace_aruco_scan_server:
  ros__parameters:
    arm_base_frame: "link0"
    ee_frame: "end_effector_link"
    camera_frame: "camera_color_optical_frame"

    pose_service_name: "/pose_to_joint_execute"
    pose_execute_mode: 5
    ik_timeout_sec: 5.0
    move_duration_sec: 5.0

    eval_link_name: "end_effector_link"
    tool_pitch_tolerance: 0.01
    wrist_tolerance: 0.0
    position_tolerance: 0.01

    # 작업영역을 볼 때 기본 pitch (0=지면평행, 아래쪽 +)
    default_view_pitch_rad: 0.6632

    # 카메라가 workspace 중심에서 얼마나 떨어져 볼지
    default_camera_standoff_m: 0.1
    default_wrist_angle_rad: 0.0

    # OpenCV VideoCapture index
    camera_device_index: 0
    camera_width: 640
    camera_height: 480

    # Intrinsic
    camera_fx: 565.31352
    camera_fy: 571.00818
    camera_cx: 277.09961
    camera_cy: 271.9845

    dist_k1: -0.411454
    dist_k2: 0.153677
    dist_p1: -0.008357
    dist_p2: 0.003162
    dist_k3: 0.000000

    aruco_dictionary: "DICT_4X4_50"
    marker_length_m: 0.025

    box_ids: [0, 1, 2]

    box_1.grasp_offset_x: 0.0
    box_1.grasp_offset_y: 0.0
    box_1.grasp_offset_z: -0.02
    box_1.yaw_offset_deg: 0.0

    box_2.grasp_offset_x: 0.0
    box_2.grasp_offset_y: 0.0
    box_2.grasp_offset_z: -0.02
    box_2.yaw_offset_deg: 0.0

    box_3.grasp_offset_x: 0.0
    box_3.grasp_offset_y: 0.0
    box_3.grasp_offset_z: -0.02
    box_3.yaw_offset_deg: 0.0
